### ISSUE TITLE
Currently doesn't do everything

### ISSUE THREAD

**Issue by tjdevries** [vigoux/architext.nvim#1]
Installed and was not able to do anything special.

**Comment by vigoux** [comment]
Hi, thanks for reporting.

It is actually a known issue we are trying to fix atm, can you try latest master and tell here if it is any better ?

**Comment by bfredl** [comment]
@maxbrunsfeld check this thing out, it actually does some cool stuff already.

**Comment by vigoux** [comment]
I think it does something now, can I close this ?

**Comment by bfredl** [comment]
does it support fennel macros yet?

**Comment by vigoux** [comment]
Nope nope, that's only the structural editing core

**Comment by tjdevries** [comment]
Please see updated issue title

**Comment by bfredl** [comment]
technically correct as everything includes fennel by definition.

**Comment by tjdevries** [comment]
I want to plus one the comment above

**Comment by vigoux** [comment]
Yo this does something now, closing.
