### ISSUE TITLE
How to use the REPL

### ISSUE THREAD

**Issue by AckslD** [vigoux/architext.nvim#2]
I'm trying to understand how to use the REPL. I started it and tried to enter either `(identifier) @i` or `((identifier) @i (#eq? @i "foo"))`, then it says `Capture i>` and I enter something but nothing really happens. After that whatever I enter it just stays at the `Query>` prompt.

Then I tried to close it with `exit` or `quit` but didn't work so I closed with `<esc>:q`. But then if I open the REPL again I get:
```
E5108: Error executing lua ...te/pack/packer/opt/architext.nvim/lua/architext/repl.lua:91: Vim:E95: Buffer with this name already exists
```

Sorry for my ignorance but would be happy to hear how to use it properly :)

**Comment by vigoux** [comment]
To be honest, I think I'll deprecate the REPL, and make the command the only way to use the plugin.
Sorry for that, but the REPL was a bad attempt at building this :wink:
