### ISSUE TITLE
Where can I add my own templates?

### ISSUE THREAD

**Issue by LeanderBlume** [vigoux/architext.nvim#8]
Where do I actually add templates? Can I do it in a config file? On the vim prompt? Or do I have to add them to `query.lua`?

Sorry if this is a stupid question and there is an easy way to add stuff to the `templates` variable in `query.lua` from a config file or something. I don't know much about the nvim plugin architecture or lua or whatever is needed for this.

**Comment by vigoux** [comment]
Hi !

There is indeed no way to add things to the templates.

For now you'd have to directly change the `templates` variable (which I think is not exposed).

**Comment by LeanderBlume** [comment]
OK, thanks for the answer! Would be nice to have this in the README.

**Comment by vigoux** [comment]
Hey, looking back at the code, it is possible to add new templates by doing:
```lua
require'architext.query'.template_query("name", "template")
```

Sorry for the delay.
